# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec3297609cb86e478c38ce23266ce6a9129c2048684be8fa0e7a9e33de2448f08d313fc78bc1d0a48cf877c01842ee86ae1fc67785fd422d82a4caf3f5336b7f

test:
  secret_key_base: f39aa6627ee70009d38ea2a6c6f0e008f17cda5ca84d7344ded1b33a85b0e64297b97293576b226ae9fb1de4e16097662471e3935cee6119272dfc94fc024622

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
